name: Dogfood
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Omashu
        uses: ./actions/setup
      - name: Test setup
        run: |
          omashu --help
      - name: Run Discover Action
        uses: ./actions/discover
      - name: Test Action Result
        run: |
          cat ${GITHUB_WORKSPACE}/commit_info.txt
